language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer update --prefer-source --dev

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml --exclude-group Functional,Performance
#  - ./vendor/bin/phpunit --group=Functional
#  - ./vendor/bin/phpunit --group=Performance
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./test/
  - ./vendor/bin/behat
